---
- name: "Group Ansible Controller hosts"
  hosts: "all"
  ignore_unreachable: true

  tasks:

    - name: "Group hosts by label"
      group_by:
        key: "label_ansible_controller"
      when: |
        "ansible_controller" in hostvars[inventory_hostname]["labels"]

- name: "Propagate Ansible project to remote nodes"
  hosts: "label_ansible_controller"
  become: true

  tasks:
    - name: "Create a timestamp variable"
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

    - name: "Create backup directory if it doesn't exist"
      file:
        path: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}_backup"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Create a zip backup of the Ansible project"
      archive:
        path: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/"
        dest: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}_backup/ansible_backup_{{ timestamp }}.zip"
        format: "zip"
        exclude_path:
          - "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/_dropfolder"
          - "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/.git"

- name: "Clean and propagate Ansible project to remote nodes"
  hosts: "label_ansible_controller"
  become: true

  tasks:
    - name: "Ensure destination directory exists"
      file:
        path: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: "Clean the destination directory"
      command: |
        rm -rf \
          {{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/* \
          {{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/.[!.]* \
          {{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/..?*
      ignore_errors: true

    - name: "Copy Ansible project to remote nodes"
      synchronize:
        src: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/"
        dest: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--chmod=D0755,F0644"

    - name: "Set permissions on Ansible project files"
      file:
        path: "{{ lookup('env', 'ANSIBLE_PROJECT_PATH') }}/"
        state: "directory"
        recurse: yes
        owner: "root"
        group: "root"
        mode: "0755"
