---
- name: "Group Ansible Controller hosts"
  hosts: "all"
  ignore_unreachable: true

  tasks:

    - name: "Group hosts by label"
      group_by:
        key: "label_ansible_controller"
      when: |
        "ansible_controller" in hostvars[inventory_hostname]["labels"]

- name: "Playbook to install Ansible dependencies"
  hosts: "label_ansible_controller"
  become: true

  tasks:
    - name: "Ensure Ansible dependencies"
      ansible.builtin.package:
        name:
          - "openssh-client"
          - "sshpass"
          - "rsync"
          - "python3"
        state: "present"
      become: true
