name: "Build & Deploy"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: true
        default: "Manual trigger"

jobs:

  build:
    name: "Build"
    uses: "panoramicovphc/reusable-workflows/.github/workflows/.reusable-build.yml@v1"

  deploy-dev:
    name: "Deploy"
    uses: "./.github/workflows/.reusable-deploy.yml"
    needs: [ "build" ]
    with:
      ENVIRONMENT_STAGE_NAME: "dev"
      ENVIRONMENT_RUNNER_LABEL: "development"
      CURRENT_PROJECT_PATH: "${{ vars.ANSIBLE_PROJECT_PATH }}"
      ARTIFACT_NAME: "${{ needs.build.outputs.ARTIFACT_NAME }}"
      HOSTINGERVPS_USER_LOGIN: "${{ vars.HOSTINGERVPS_USER_LOGIN }}"
    secrets:
      HOSTINGERVPS_USER_PASSWORD: "${{ secrets.HOSTINGERVPS_USER_PASSWORD }}"
      CF_TUNNEL_TOKEN_HOSTINGERVPS: "${{ secrets.CF_TUNNEL_TOKEN_HOSTINGERVPS }}"
