name: "Build & Deploy"
run-name: "${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}"

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: true
        default: "Manual trigger"

env:
  ANSIBLE_PROJECT_PATH: "${{ vars.ANSIBLE_PROJECT_PATH }}"

jobs:

  build:
    name: "Build"
    uses: "panoramicovphc/reusable-workflows/.github/workflows/.reusable-build.yml@v1"
    with:
      HOST_USER_LOGIN: "${{ vars.HOSTINGERVPS_USER_LOGIN }}"
    secrets:
      HOST_USER_PASSWORD: "${{ secrets.HOSTINGERVPS_USER_PASSWORD }}"
      HOST_CF_TUNNEL_TOKEN: "${{ secrets.CF_TUNNEL_TOKEN_HOSTINGERVPS }}"

  deploy-dev:
    name: "deploy-dev"
    uses: "./.github/workflows/.reusable-deploy.yml"
    runs-on: [ "panoramicovphc", "self-hosted", "development" ]
    needs: [ "build" ]
    with:
      ENVIRONMENT_STAGE_NAME: "dev"
      ARTIFACT_NAME: "${{ needs.build.outputs.ARTIFACT_NAME }}"
      ARTIFACT_PATH: "${{ needs.build.outputs.ARTIFACT_PATH }}"
